require("wi.core.options")
require("wi.core.remap")
require("wi.core.plugins")
require("wi.core.colorscheme")
require("wi.core.lsp-config")

require("wi.plugin-configs.nvim-tree")
require("wi.plugin-configs.telescope")
require("wi.plugin-configs.treesitter")
require("wi.plugin-configs.mason")
require("wi.plugin-configs.gitsigns")
