require("wi.core.options")
require("wi.core.remap")
require("wi.core.plugins")
require("wi.core.colorscheme")
require("wi.core.lsp-config")

require("wi.plugin-configs.nvim-tree")
require("wi.plugin-configs.telescope")
require("wi.plugin-configs.treesitter")
require("wi.plugin-configs.mason")
require("wi.plugin-configs.gitsigns")
require("wi.plugin-configs.lualine")
require("wi.plugin-configs.indent-blankline")
require("wi.plugin-configs.nvim-cmp")
require("wi.plugin-configs.diffview")
require("wi.plugin-configs.barbar")
